image: java:8

before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew -g cache/.gradle clean assemble

test:
  stage: test
  script:
    - ./gradlew -g cache/.gradle check
