package rdf;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ventyl' at '1/8/17 2:07 PM' with Gradle 2.14.1
 *
 * @author ventyl, @date 1/8/17 2:07 PM
 */

import java.awt.Dimension;
import java.awt.EventQueue;

import javax.swing.JFrame;

public class Library {
    
    public void showGraph() {
    	EventQueue.invokeLater(() -> {
	       	 JFrame frame = new RDFFrame("Simple Graph View");
	       	 frame.setSize(new Dimension(800,600));
	       	 frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
	         frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	         frame.setVisible(true);
        });

    }
    
    public static void main(String[] args) {
    	Library l = new Library();
    	l.showGraph();
    }
}
