/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ventyl' at '1/8/17 2:07 PM' with Gradle 2.14.1
 *
 * @author ventyl, @date 1/8/17 2:07 PM
 */

import java.awt.Dimension;
import java.awt.EventQueue;

import javax.swing.JFrame;

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.RDFNode;
import org.apache.jena.rdf.model.ResIterator;
import org.apache.jena.rdf.model.Resource;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Statement;
import org.apache.jena.rdf.model.StmtIterator;
import org.apache.jena.vocabulary.VCARD;

import edu.uci.ics.jung.algorithms.layout.CircleLayout;
import edu.uci.ics.jung.algorithms.layout.Layout;
import edu.uci.ics.jung.graph.DirectedSparseGraph;
import edu.uci.ics.jung.graph.Graph;
import edu.uci.ics.jung.graph.SparseMultigraph;
import edu.uci.ics.jung.visualization.BasicVisualizationServer;
import edu.uci.ics.jung.visualization.VisualizationImageServer;

public class Library {
	public Model createModel() {
		String johnURI = "person://john";
    	String alexURI = "person://alex";
    	String benURI = "person://ben";
    	Model m = ModelFactory.createDefaultModel();
    	Resource john = m.createResource(johnURI).addProperty(VCARD.NAME, "John");
    	Resource alex = m.createResource(alexURI).addProperty(VCARD.NAME, "Alex");
    	m.createResource(benURI).addProperty(VCARD.NAME, "Ben");
    	john.addProperty(VCARD.Family, alex);
    	alex.addProperty(VCARD.Family,john);
    	return m;
	}
    public boolean someLibraryMethod() {
    	Model m = createModel();
    	StmtIterator stmtIter = m.listStatements();
    	while(stmtIter.hasNext()) {
    		Statement statement = stmtIter.nextStatement();
    		Resource subject = statement.getSubject();
    		Property predicate = statement.getPredicate();
    		RDFNode object = statement.getObject();
    		
    		System.out.print(subject.toString());
    	    System.out.print(" " + predicate.toString() + " ");
    		if (object instanceof Resource) {
		       System.out.print(object.toString());
		    } else {
		        // object is a literal
		        System.out.print(" \"" + object.toString() + "\"");
		    }
    		System.out.println("");
    	}
    	System.out.println("RDF:");
    	m.write(System.out);
    	System.out.println("Subjects:");
    	ResIterator subIter = m.listSubjects();
    	while(subIter.hasNext()) {
    		Resource r = subIter.nextResource();
    		System.out.println(r.toString());
    	}
        return true;
    }
    
    public Graph<Integer, String>  createGraph() {
        Graph<Integer, String> g;
    	// Graph<V, E> where V is the type of the vertices and E is the type of the edges
        g = new SparseMultigraph<Integer, String>();
        // Add some vertices. From above we defined these to be type Integer.
        g.addVertex((Integer)1);
        g.addVertex((Integer)2);
        g.addVertex((Integer)3); 
        // Note that the default is for undirected edges, our Edges are Strings.
        g.addEdge("Edge-A", 1, 2); // Note that Java 1.5 auto-boxes primitives
        g.addEdge("Edge-B", 2, 3);
        return g;
    }
    
    public void showGraph() {
    	EventQueue.invokeLater(() -> {
        	 Graph<Integer, String> graph = createGraph();
	       	 Layout<Integer, String> layout = new CircleLayout(graph);
	       	 layout.setSize(new Dimension(300,300)); // sets the initial size of the space
	       	 // The BasicVisualizationServer<V,E> is parameterized by the edge types
	       	 BasicVisualizationServer<Integer,String> vv =
	       	 new BasicVisualizationServer<Integer,String>(layout);
	       	 vv.setPreferredSize(new Dimension(350,350)); //Sets the viewing area size
	
	       	 JFrame frame = new JFrame("Simple Graph View");
	       	 frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	       	 frame.getContentPane().add(vv);
	       	 frame.pack();
	       	 frame.setVisible(true);
        });

    }
    
    public static void main(String[] args) {
    	Library l = new Library();
    	l.someLibraryMethod();
    	l.showGraph();
    }
}
